#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "tc.string.h"

int
show_usage(const char *program)
{
    printf("\
%s [filename]\n\
Markdown like document generator.\n\
keywords:\n\
  @function, @class, @interface, @method, @param, @throws, @return, @property\n\
", program);
    return 1;
}

int main(int argc, char *argv[])
{
    if (argc != 2) {
        return show_usage(argv[0]);
    }

    FILE *fp;
    fp = fopen(argv[1], "r");
    if (fp == NULL) {
        perror(argv[0]);
        return 1;
    }

    char *data, *found, *out;
    int isComment;

    isComment = 0;
    while ((data = read_line(fp)) != NULL) {
        if (strstr(data, "/**") != NULL) {
            isComment = 1;
            continue;
        }
        if (strstr(data, "*/") != NULL) {
            isComment = 0;
            printf("\n");
            continue;
        }
        if (isComment) {
            found = strstr(data, "*");
            if (found) {
                out = found + 1;
            } else {
                out = data;
            }

            found = strstr(data, "@function");
            if (found) {
                out = found;
                printf("## %s\n", out);
                continue;
            }

            found = strstr(data, "@class");
            if (found) {
                out = found;
                printf("# %s\n", out);
                continue;
            }

            found = strstr(data, "@interface");
            if (found) {
                out = found;
                printf("# %s\n", out);
                continue;
            }

            found = strstr(data, "@method");
            if (found) {
                out = found;
                printf("## %s\n", out);
                continue;
            }

            found = strstr(data, "@param");
            if (found) {
                out = found;
                printf("* %s\n", out);
                continue;
            }

            found = strstr(data, "@return");
            if (found) {
                out = found;
                printf("* %s\n", out);
                continue;
            }

            found = strstr(data, "@throws");
            if (found) {
                out = found;
                printf("* %s\n", out);
                continue;
            }

            found = strstr(data, "@property");
            if (found) {
                out = found;
                printf("## %s\n", out);
                continue;
            }

            printf("%s\n", out);
        }
        if (data) {
            free(data);
        }
    }

    fclose(fp);
    fputs("\n\n\n>Generated by [tc.make_doc_class](https://github.com/ISSKJ/toolc-dist/)\n", stdout);

    return 0;
}
